### PR TITLE
To-do List

### PR DESCRIPTION
**Pull request by realisticattorney**
The purpose of this project was to build an app where users can creates lists called projects, and within them create tasks, each with it's own title, description, date and priority level.

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- Good introduction :+1:
- It uses localStorage  :+1:
- It uses webpack :+1:

To Improve :factory_worker: (REQUIRED):

- [ ] In your package.json, please set the `mode` option to '`development`' or '`production`' to enable **defaults** for each environment. It is necessary that you add commands like `build`, `development` inside ``scripts`'.
Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/)):
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

- [ ] Please, delete files not related to your project and add them in the `.gitignore` file as you don't need them.
- [ ] Do not use Window.alert() or Window.confirm(). It’s ugly, impossible to style, stop code execution and display differently on different browsers. Use custom modal instead. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/alert_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/javascript-module-v-10/166782/path/step/97634928/))


- [ ] Good readme file but I suggest you use tools like grammarly that will help you in your grammar.
- [ ] Your MIT licence link is broken, It will be nice if you fix it. Keep in mind that the first thing that user checks is your readme file.

Nice to have :
- [ ] I suggest that you polish your Getting Started instruction in order to make it easy to read.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @realisticattorney and @luisvinicius09  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to address all of requested changes from the previous review inorder to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Please, delete files not related to your project and add them in the `.gitignore` file as you don't need them. => This is not implemented successfully, you should remove the `.DS_Store` file, you can achieve that by running `git rm -rf .DS_Store` and then add it to .gitignore, and commit changes
- [ ] Your MIT licence link is still broken, It will be nice if you fix it. Keep in mind that the first thing that user checks is your readme file.
- [ ] Good readme file but I suggest you use tools like grammarly that will help you in your grammar. => Some portion of your readme file has grammar issues, you need to fix them out. You can use [this tool](https://app.grammarly.com/) to be able to spot them out
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by realisticattorney** [comment]
I've created the license from GitHub directly, selecting the template and everything. Still, it doesn't show me the MIT banner when I open the file. I will issue a bug report. But I don't know how long that's going to take.

**Review by bellom — APPROVED** [review]
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
